// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: artifacts.sql

package store

import (
	"context"
)

const getArtifact = `-- name: GetArtifact :one
SELECT digest, size, media_type, class, created_at FROM artifacts WHERE digest = ?
`

func (q *Queries) GetArtifact(ctx context.Context, digest string) (Artifact, error) {
	row := q.db.QueryRowContext(ctx, getArtifact, digest)
	var i Artifact
	err := row.Scan(
		&i.Digest,
		&i.Size,
		&i.MediaType,
		&i.Class,
		&i.CreatedAt,
	)
	return i, err
}

const insertArtifact = `-- name: InsertArtifact :exec
INSERT INTO artifacts (digest, size, media_type, class, created_at)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT(digest) DO NOTHING
`

type InsertArtifactParams struct {
	Digest    string
	Size      int64
	MediaType string
	Class     string
	CreatedAt string
}

// Content is immutable and named by its digest, so a repeated put of
// identical bytes is a no-op rather than a conflict.
func (q *Queries) InsertArtifact(ctx context.Context, arg InsertArtifactParams) error {
	_, err := q.db.ExecContext(ctx, insertArtifact,
		arg.Digest,
		arg.Size,
		arg.MediaType,
		arg.Class,
		arg.CreatedAt,
	)
	return err
}

const listArtifacts = `-- name: ListArtifacts :many
SELECT digest, size, media_type, class, created_at FROM artifacts ORDER BY created_at, digest
`

func (q *Queries) ListArtifacts(ctx context.Context) ([]Artifact, error) {
	rows, err := q.db.QueryContext(ctx, listArtifacts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Artifact{}
	for rows.Next() {
		var i Artifact
		if err := rows.Scan(
			&i.Digest,
			&i.Size,
			&i.MediaType,
			&i.Class,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
