// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: attempts.sql

package store

import (
	"context"
)

const insertAttempt = `-- name: InsertAttempt :exec

INSERT INTO attempts (
  attempt_id, packet_id, transition, argv, attempted_at, duration_ms,
  exit_code, marker, reason, record_kind, exhaustiveness,
  event_appended, events_before, events_after,
  head_before, head_after, stage_before, stage_after,
  stdout_tail, stderr_tail, stdout_sha256, stderr_sha256, tool_sha256
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertAttemptParams struct {
	AttemptID      string
	PacketID       string
	Transition     string
	Argv           string
	AttemptedAt    string
	DurationMs     int64
	ExitCode       int64
	Marker         string
	Reason         string
	RecordKind     string
	Exhaustiveness string
	EventAppended  int64
	EventsBefore   int64
	EventsAfter    int64
	HeadBefore     string
	HeadAfter      string
	StageBefore    string
	StageAfter     string
	StdoutTail     string
	StderrTail     string
	StdoutSha256   string
	StderrSha256   string
	ToolSha256     string
}

// Append-only. There is deliberately no update or delete here: an attempt is a
// fact about a moment, and a later attempt is a new row.
func (q *Queries) InsertAttempt(ctx context.Context, arg InsertAttemptParams) error {
	_, err := q.db.ExecContext(ctx, insertAttempt,
		arg.AttemptID,
		arg.PacketID,
		arg.Transition,
		arg.Argv,
		arg.AttemptedAt,
		arg.DurationMs,
		arg.ExitCode,
		arg.Marker,
		arg.Reason,
		arg.RecordKind,
		arg.Exhaustiveness,
		arg.EventAppended,
		arg.EventsBefore,
		arg.EventsAfter,
		arg.HeadBefore,
		arg.HeadAfter,
		arg.StageBefore,
		arg.StageAfter,
		arg.StdoutTail,
		arg.StderrTail,
		arg.StdoutSha256,
		arg.StderrSha256,
		arg.ToolSha256,
	)
	return err
}

const listAllAttempts = `-- name: ListAllAttempts :many
SELECT attempt_id, packet_id, transition, argv, attempted_at, duration_ms, exit_code, marker, reason, record_kind, exhaustiveness, event_appended, events_before, events_after, head_before, head_after, stage_before, stage_after, stdout_tail, stderr_tail, stdout_sha256, stderr_sha256, tool_sha256 FROM attempts ORDER BY packet_id, attempted_at, attempt_id
`

func (q *Queries) ListAllAttempts(ctx context.Context) ([]Attempt, error) {
	rows, err := q.db.QueryContext(ctx, listAllAttempts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Attempt{}
	for rows.Next() {
		var i Attempt
		if err := rows.Scan(
			&i.AttemptID,
			&i.PacketID,
			&i.Transition,
			&i.Argv,
			&i.AttemptedAt,
			&i.DurationMs,
			&i.ExitCode,
			&i.Marker,
			&i.Reason,
			&i.RecordKind,
			&i.Exhaustiveness,
			&i.EventAppended,
			&i.EventsBefore,
			&i.EventsAfter,
			&i.HeadBefore,
			&i.HeadAfter,
			&i.StageBefore,
			&i.StageAfter,
			&i.StdoutTail,
			&i.StderrTail,
			&i.StdoutSha256,
			&i.StderrSha256,
			&i.ToolSha256,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttempts = `-- name: ListAttempts :many
SELECT attempt_id, packet_id, transition, argv, attempted_at, duration_ms, exit_code, marker, reason, record_kind, exhaustiveness, event_appended, events_before, events_after, head_before, head_after, stage_before, stage_after, stdout_tail, stderr_tail, stdout_sha256, stderr_sha256, tool_sha256 FROM attempts WHERE packet_id = ? ORDER BY attempted_at, attempt_id
`

func (q *Queries) ListAttempts(ctx context.Context, packetID string) ([]Attempt, error) {
	rows, err := q.db.QueryContext(ctx, listAttempts, packetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Attempt{}
	for rows.Next() {
		var i Attempt
		if err := rows.Scan(
			&i.AttemptID,
			&i.PacketID,
			&i.Transition,
			&i.Argv,
			&i.AttemptedAt,
			&i.DurationMs,
			&i.ExitCode,
			&i.Marker,
			&i.Reason,
			&i.RecordKind,
			&i.Exhaustiveness,
			&i.EventAppended,
			&i.EventsBefore,
			&i.EventsAfter,
			&i.HeadBefore,
			&i.HeadAfter,
			&i.StageBefore,
			&i.StageAfter,
			&i.StdoutTail,
			&i.StderrTail,
			&i.StdoutSha256,
			&i.StderrSha256,
			&i.ToolSha256,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
