// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: claims.sql

package store

import (
	"context"
)

const deleteClaim = `-- name: DeleteClaim :exec
DELETE FROM claims WHERE packet_id = ?
`

func (q *Queries) DeleteClaim(ctx context.Context, packetID string) error {
	_, err := q.db.ExecContext(ctx, deleteClaim, packetID)
	return err
}

const getClaim = `-- name: GetClaim :one
SELECT packet_id, owner, note, acquired_at, expires_at FROM claims WHERE packet_id = ?
`

func (q *Queries) GetClaim(ctx context.Context, packetID string) (Claim, error) {
	row := q.db.QueryRowContext(ctx, getClaim, packetID)
	var i Claim
	err := row.Scan(
		&i.PacketID,
		&i.Owner,
		&i.Note,
		&i.AcquiredAt,
		&i.ExpiresAt,
	)
	return i, err
}

const listClaims = `-- name: ListClaims :many
SELECT packet_id, owner, note, acquired_at, expires_at FROM claims ORDER BY packet_id
`

func (q *Queries) ListClaims(ctx context.Context) ([]Claim, error) {
	rows, err := q.db.QueryContext(ctx, listClaims)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Claim{}
	for rows.Next() {
		var i Claim
		if err := rows.Scan(
			&i.PacketID,
			&i.Owner,
			&i.Note,
			&i.AcquiredAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnclaimedPackets = `-- name: ListUnclaimedPackets :many
SELECT p.packet_id
FROM packets p
LEFT JOIN claims c ON c.packet_id = p.packet_id
WHERE c.packet_id IS NULL OR c.expires_at <= ?
ORDER BY p.created_at, p.packet_id
`

// Packets nobody currently holds: never claimed, or claimed by a harness whose
// lease has run out. Times are stored fixed-width so this string comparison is
// a chronological one.
func (q *Queries) ListUnclaimedPackets(ctx context.Context, expiresAt string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listUnclaimedPackets, expiresAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var packet_id string
		if err := rows.Scan(&packet_id); err != nil {
			return nil, err
		}
		items = append(items, packet_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const putClaim = `-- name: PutClaim :exec
INSERT INTO claims (packet_id, owner, note, acquired_at, expires_at)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT(packet_id) DO UPDATE SET
  owner       = excluded.owner,
  note        = excluded.note,
  acquired_at = excluded.acquired_at,
  expires_at  = excluded.expires_at
`

type PutClaimParams struct {
	PacketID   string
	Owner      string
	Note       string
	AcquiredAt string
	ExpiresAt  string
}

func (q *Queries) PutClaim(ctx context.Context, arg PutClaimParams) error {
	_, err := q.db.ExecContext(ctx, putClaim,
		arg.PacketID,
		arg.Owner,
		arg.Note,
		arg.AcquiredAt,
		arg.ExpiresAt,
	)
	return err
}
