// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package store

import (
	"context"
)

const countEvents = `-- name: CountEvents :one
SELECT COUNT(*) FROM events WHERE packet_id = ?
`

func (q *Queries) CountEvents(ctx context.Context, packetID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countEvents, packetID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getChainTail = `-- name: GetChainTail :one
SELECT packet_id, seq, hash, prev, time, payload, state_sha256 FROM events WHERE packet_id = ? ORDER BY seq DESC LIMIT 1
`

// Chain tail. Returns sql.ErrNoRows for a packet with no events, which the
// caller reads as "expect seq 1 with a zero prev".
func (q *Queries) GetChainTail(ctx context.Context, packetID string) (Event, error) {
	row := q.db.QueryRowContext(ctx, getChainTail, packetID)
	var i Event
	err := row.Scan(
		&i.PacketID,
		&i.Seq,
		&i.Hash,
		&i.Prev,
		&i.Time,
		&i.Payload,
		&i.StateSha256,
	)
	return i, err
}

const getEvent = `-- name: GetEvent :one
SELECT packet_id, seq, hash, prev, time, payload, state_sha256 FROM events WHERE packet_id = ? AND seq = ?
`

type GetEventParams struct {
	PacketID string
	Seq      int64
}

func (q *Queries) GetEvent(ctx context.Context, arg GetEventParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, getEvent, arg.PacketID, arg.Seq)
	var i Event
	err := row.Scan(
		&i.PacketID,
		&i.Seq,
		&i.Hash,
		&i.Prev,
		&i.Time,
		&i.Payload,
		&i.StateSha256,
	)
	return i, err
}

const insertEvent = `-- name: InsertEvent :exec
INSERT INTO events (packet_id, seq, hash, prev, time, payload, state_sha256)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertEventParams struct {
	PacketID    string
	Seq         int64
	Hash        string
	Prev        string
	Time        string
	Payload     string
	StateSha256 string
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) error {
	_, err := q.db.ExecContext(ctx, insertEvent,
		arg.PacketID,
		arg.Seq,
		arg.Hash,
		arg.Prev,
		arg.Time,
		arg.Payload,
		arg.StateSha256,
	)
	return err
}

const listEvents = `-- name: ListEvents :many
SELECT packet_id, seq, hash, prev, time, payload, state_sha256 FROM events WHERE packet_id = ? ORDER BY seq
`

func (q *Queries) ListEvents(ctx context.Context, packetID string) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listEvents, packetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.PacketID,
			&i.Seq,
			&i.Hash,
			&i.Prev,
			&i.Time,
			&i.Payload,
			&i.StateSha256,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
