// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

type Artifact struct {
	Digest    string
	Size      int64
	MediaType string
	Class     string
	CreatedAt string
}

type Claim struct {
	PacketID   string
	Owner      string
	Note       string
	AcquiredAt string
	ExpiresAt  string
}

type Event struct {
	PacketID    string
	Seq         int64
	Hash        string
	Prev        string
	Time        string
	Payload     string
	StateSha256 string
}

type Packet struct {
	PacketID  string
	CreatedAt string
	Objective string
}

type PacketState struct {
	PacketID    string
	StateJson   string
	StateSha256 string
	LastSeq     int64
	LastHash    string
}

type Session struct {
	PacketID   string
	Role       string
	Cycle      int64
	Client     string
	SessionID  string
	AgentPath  string
	Parent     string
	Pid        int64
	Status     string
	Reason     string
	Note       string
	StartedAt  string
	LastSeen   string
	TtlSeconds int64
}
