// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: packet_state.sql

package store

import (
	"context"
)

const getPacketState = `-- name: GetPacketState :one
SELECT packet_id, state_json, state_sha256, last_seq, last_hash FROM packet_state WHERE packet_id = ?
`

func (q *Queries) GetPacketState(ctx context.Context, packetID string) (PacketState, error) {
	row := q.db.QueryRowContext(ctx, getPacketState, packetID)
	var i PacketState
	err := row.Scan(
		&i.PacketID,
		&i.StateJson,
		&i.StateSha256,
		&i.LastSeq,
		&i.LastHash,
	)
	return i, err
}

const upsertPacketState = `-- name: UpsertPacketState :exec
INSERT INTO packet_state (packet_id, state_json, state_sha256, last_seq, last_hash)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT(packet_id) DO UPDATE SET
  state_json   = excluded.state_json,
  state_sha256 = excluded.state_sha256,
  last_seq     = excluded.last_seq,
  last_hash    = excluded.last_hash
`

type UpsertPacketStateParams struct {
	PacketID    string
	StateJson   string
	StateSha256 string
	LastSeq     int64
	LastHash    string
}

// The projected current state is replaced wholesale in the same transaction
// that appends the event producing it. Events are never updated; this row is
// a derived view and carries the seq and hash it was derived from so a
// disagreement with the chain is detectable.
func (q *Queries) UpsertPacketState(ctx context.Context, arg UpsertPacketStateParams) error {
	_, err := q.db.ExecContext(ctx, upsertPacketState,
		arg.PacketID,
		arg.StateJson,
		arg.StateSha256,
		arg.LastSeq,
		arg.LastHash,
	)
	return err
}
