// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"
)

type Querier interface {
	ArchiveWorkerSession(ctx context.Context, arg ArchiveWorkerSessionParams) error
	CountEvents(ctx context.Context, packetID string) (int64, error)
	CreatePacket(ctx context.Context, arg CreatePacketParams) error
	DeleteClaim(ctx context.Context, packetID string) error
	GetArtifact(ctx context.Context, digest string) (Artifact, error)
	// Chain tail. Returns sql.ErrNoRows for a packet with no events, which the
	// caller reads as "expect seq 1 with a zero prev".
	GetChainTail(ctx context.Context, packetID string) (Event, error)
	GetClaim(ctx context.Context, packetID string) (Claim, error)
	GetEvent(ctx context.Context, arg GetEventParams) (Event, error)
	GetPacket(ctx context.Context, packetID string) (Packet, error)
	GetPacketState(ctx context.Context, packetID string) (PacketState, error)
	GetWorkerSession(ctx context.Context, arg GetWorkerSessionParams) (WorkerSession, error)
	// Content is immutable and named by its digest, so a repeated put of
	// identical bytes is a no-op rather than a conflict.
	InsertArtifact(ctx context.Context, arg InsertArtifactParams) error
	// Append-only. There is deliberately no update or delete here: an attempt is a
	// fact about a moment, and a later attempt is a new row.
	InsertAttempt(ctx context.Context, arg InsertAttemptParams) error
	InsertEvent(ctx context.Context, arg InsertEventParams) error
	ListAllAttempts(ctx context.Context) ([]Attempt, error)
	ListArtifacts(ctx context.Context) ([]Artifact, error)
	ListAttempts(ctx context.Context, packetID string) ([]Attempt, error)
	ListClaims(ctx context.Context) ([]Claim, error)
	ListEvents(ctx context.Context, packetID string) ([]Event, error)
	ListPackets(ctx context.Context) ([]Packet, error)
	// Packets nobody currently holds: never claimed, or claimed by a harness whose
	// lease has run out. Times are stored fixed-width so this string comparison is
	// a chronological one.
	ListUnclaimedPackets(ctx context.Context, expiresAt string) ([]string, error)
	ListWorkerSessionHistory(ctx context.Context, packetID string) ([]WorkerSessionHistory, error)
	ListWorkerSessions(ctx context.Context) ([]WorkerSession, error)
	ListWorkerSessionsForPacket(ctx context.Context, packetID string) ([]WorkerSession, error)
	PutClaim(ctx context.Context, arg PutClaimParams) error
	PutWorkerSession(ctx context.Context, arg PutWorkerSessionParams) error
	// The projected current state is replaced wholesale in the same transaction
	// that appends the event producing it. Events are never updated; this row is
	// a derived view and carries the seq and hash it was derived from so a
	// disagreement with the chain is detectable.
	UpsertPacketState(ctx context.Context, arg UpsertPacketStateParams) error
}

var _ Querier = (*Queries)(nil)
