// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package store

import (
	"context"
)

const getSession = `-- name: GetSession :one
SELECT packet_id, role, cycle, client, session_id, agent_path, parent, pid, status, reason, note, started_at, last_seen, ttl_seconds FROM sessions WHERE packet_id = ? AND role = ? AND cycle = ?
`

type GetSessionParams struct {
	PacketID string
	Role     string
	Cycle    int64
}

func (q *Queries) GetSession(ctx context.Context, arg GetSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSession, arg.PacketID, arg.Role, arg.Cycle)
	var i Session
	err := row.Scan(
		&i.PacketID,
		&i.Role,
		&i.Cycle,
		&i.Client,
		&i.SessionID,
		&i.AgentPath,
		&i.Parent,
		&i.Pid,
		&i.Status,
		&i.Reason,
		&i.Note,
		&i.StartedAt,
		&i.LastSeen,
		&i.TtlSeconds,
	)
	return i, err
}

const listSessions = `-- name: ListSessions :many
SELECT packet_id, role, cycle, client, session_id, agent_path, parent, pid, status, reason, note, started_at, last_seen, ttl_seconds FROM sessions ORDER BY packet_id, role, cycle
`

func (q *Queries) ListSessions(ctx context.Context) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, listSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.PacketID,
			&i.Role,
			&i.Cycle,
			&i.Client,
			&i.SessionID,
			&i.AgentPath,
			&i.Parent,
			&i.Pid,
			&i.Status,
			&i.Reason,
			&i.Note,
			&i.StartedAt,
			&i.LastSeen,
			&i.TtlSeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionsForPacket = `-- name: ListSessionsForPacket :many
SELECT packet_id, role, cycle, client, session_id, agent_path, parent, pid, status, reason, note, started_at, last_seen, ttl_seconds FROM sessions WHERE packet_id = ? ORDER BY role, cycle
`

func (q *Queries) ListSessionsForPacket(ctx context.Context, packetID string) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, listSessionsForPacket, packetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.PacketID,
			&i.Role,
			&i.Cycle,
			&i.Client,
			&i.SessionID,
			&i.AgentPath,
			&i.Parent,
			&i.Pid,
			&i.Status,
			&i.Reason,
			&i.Note,
			&i.StartedAt,
			&i.LastSeen,
			&i.TtlSeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const putSession = `-- name: PutSession :exec
INSERT INTO sessions (
  packet_id, role, cycle, client, session_id, agent_path, parent, pid,
  status, reason, note, started_at, last_seen, ttl_seconds
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(packet_id, role, cycle) DO UPDATE SET
  client      = excluded.client,
  session_id  = excluded.session_id,
  agent_path  = excluded.agent_path,
  parent      = excluded.parent,
  pid         = excluded.pid,
  status      = excluded.status,
  reason      = excluded.reason,
  note        = excluded.note,
  started_at  = excluded.started_at,
  last_seen   = excluded.last_seen,
  ttl_seconds = excluded.ttl_seconds
`

type PutSessionParams struct {
	PacketID   string
	Role       string
	Cycle      int64
	Client     string
	SessionID  string
	AgentPath  string
	Parent     string
	Pid        int64
	Status     string
	Reason     string
	Note       string
	StartedAt  string
	LastSeen   string
	TtlSeconds int64
}

func (q *Queries) PutSession(ctx context.Context, arg PutSessionParams) error {
	_, err := q.db.ExecContext(ctx, putSession,
		arg.PacketID,
		arg.Role,
		arg.Cycle,
		arg.Client,
		arg.SessionID,
		arg.AgentPath,
		arg.Parent,
		arg.Pid,
		arg.Status,
		arg.Reason,
		arg.Note,
		arg.StartedAt,
		arg.LastSeen,
		arg.TtlSeconds,
	)
	return err
}
