// Package store owns the control-plane SQLite database: opening it with the
// required pragmas, applying embedded migrations, and the sqlc-generated query
// layer.
//
// Exactly one process — flowd — opens this database (decisions.md D2). The
// driver is modernc.org/sqlite, the only runtime dependency permitted by D4.
//
// Files named *.sql.go, db.go, models.go, and querier.go in this package are
// generated by sqlc from queries/ against migrations/. Regenerate with
// `make sqlc`; never hand-edit them.
package store

import (
	"embed"

	// Registers the pure-Go "sqlite" driver. No cgo (decisions.md D4).
	_ "modernc.org/sqlite"
)

// DriverName is the database/sql driver registered by modernc.org/sqlite.
const DriverName = "sqlite"

// migrationsFS holds the numbered schema migrations. They are embedded so a
// deployed binary carries its own schema and cannot be applied from files that
// drifted from the build.
//
//go:embed migrations/*.sql
var migrationsFS embed.FS
